name: build

on:
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js for semantic-release
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Semantic release
        run: npm_config_yes=true npx semantic-release

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension
          path: extension/
          retention-days: 5
