name: package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GOOGLE_OAUTH2_CLIENT_ID_PROD: xxx
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Grab current tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Replace the v prefix in version tag
        uses: mad9000/actions-find-and-replace-string@1
        id: version
        with:
          source: ${{ steps.vars.outputs.tag }}
          find: 'v'
          replace: ''

      - name: Download artifact from build step (i.e. the fully built extension)
        uses: actions/checkout@v2
        with:
          name: chrome-extension
          path: ./build-output/

      - name: Display structure of downloaded files
        run: ls -lashrt ./build-output/

      - name: Bump versions in package.json and manifest.json
        run: |
          npm_config_yes=true npx dot-json package.json version ${{ steps.version.outputs.value }}
          npm_config_yes=true npx dot-json manifest.json version ${{ steps.version.outputs.value }}
          npm_config_yes=true npx dot-json build-output/package.json version ${{ steps.version.outputs.value }}
          npm_config_yes=true npx dot-json build-output/manifest.json version ${{ steps.version.outputs.value }}

      - name: Commit bumped versions back to Git after tag is created
        uses: EndBug/add-and-commit@v7
        with:
          add: 'package.json manifest.json'
          default_author: github_actions
          branch: main
          message: 'version: 🏷 Auto-update version on release.'
          pull_strategy: 'NO-PULL'

      - name: Package local flavour of extension ZIP file
        run: zip -r oslash-extension-local.zip build-output/

      - name: Attach local flavour of extension ZIP file to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: oslash-extension-local.zip
          tag: ${{ steps.vars.outputs.tag }}
          overwrite: true

      # The prod-only store flavour has 2 differences from the local flavour.
      # 1. The manifest.json > oauth2.client_id key is different from prod.
      # 2. The manifest.json > key field is removed.
      - name: Package store flavour of extension ZIP file
        run: |
          npm_config_yes=true npx dot-json build-output/manifest.json oauth2.client_id ${{ env.GOOGLE_OAUTH2_CLIENT_ID_PROD }}
          npm_config_yes=true npx dot-json build-output/manifest.json key --delete
          zip -r oslash-extension-store.zip build-output/

      - name: Attach store flavour of extension ZIP file to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: oslash-extension-store.zip
          tag: ${{ steps.vars.outputs.tag }}
          overwrite: true
