name: publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      EXTENSION_ID: gpljeioabgadbidbkcbhjjglpinfhmal
      GOOGLE_OAUTH2_CLIENT_ID_PROD: xxx
    steps:
      - name: Debug event and action context
        uses: hmarr/debug-action@v2

      - name: ⤵️ Download extension ZIP file from releases
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "tags/${{ github.event.inputs.ref }}"
          file: oslash-extension-store.zip
          target: ./
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug downloaded attachment
        run: ls -lsrhta

      # @see https://developer.chrome.com/docs/webstore/using_webstore_api/
      # @see https://github.com/DrewML/chrome-webstore-upload-cli#web-store-upload-cli
      - name: 🚀 Publish extension to Chrome store
        run: |
          npm_config_yes=true npx chrome-webstore-upload-cli --source oslash-extension-store.zip --extension-id ${{ env.EXTENSION_ID }} --client-id ${{ env.GOOGLE_OAUTH2_CLIENT_ID_PROD }} --client-secret ${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET_PROD }} --refresh-token ${{ secrets.GOOGLE_OAUTH2_CLIENT_REFRESH_TOKEN_PROD }} --auto-publish
