name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish chrome extension
    runs-on: ubuntu-latest
    steps:
      - name: checking out repository ⏬
        uses: actions/checkout@master
      - name: installing node ⚙️
        uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: Bump versions
        run: |
          node -e "var p = require('./extension/package.json'); p.version = '${{ github.event.release.tag_name }}'; console.log(JSON.stringify(p, null, 4));" > /tmp/package.json
          node -e "var m = require('./extension/manifest.json'); m.version = '${{ github.event.release.tag_name }}'; console.log(JSON.stringify(p, null, 4));" > /tmp/manifest.json
          mv /tmp/package.json ./extension/package.json
          mv /tmp/manifest.json ./extension/manifest.json
          rm -f /tmp/package.json /tmp/manifest.json
      - name: upload tarball to archives ⬆️
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension
          path: extension/
          retention-days: 5
